site_name: TWE Design System
repo_url: https://github.com/hackforla/internship-website-design-system
site_url: https://hackforla.github.io/internship-website-design-system/

nav:
  - Getting Started: index.md
  - Styles:
      - Typography: type-scale.md
      
  - Components:
      - Accordion: accordion.md
      - Button: buttons.md
      - Checkbox: checkbox.md
      - Input Fields: input-fields.md
      - Grid System: grid-system.md
      - Pagination: pagination.md
      - Radio Button: radio.md
      - Text Area: text-area.md
      - Toggles: toggles.md
      - Dropdown: dropdowns.md

  - Material Prototype:
      - Material Toggle: material-prototype/toggle.md
      - Material Checkbox: material-prototype/checkbox.md
      - Material Input Field: material-prototype/input.md
      - Evaluation Summary: material-prototype/material3-assesment.md
      - Token Setup: material-prototype/token-setup.md


plugins:
  - search:
      lang: en

theme:
  name: material
  font:
    text: roboto
  logo: Logo Flatten White.png
  features:
    - navigation.instant
    - navigation.path
    - content.code.copy
    - content.code.select
  palette:
    primary: white
  custom_dir: docs/overrides

extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons+Outlined
  - dist/main.css
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js
  - javascript/pagination.js
  - javascript/dropdown.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
